<a href="https://colab.research.google.com/github/GalynaGnatenko/GnatenkoGalyna/blob/main/%D0%93%D0%BD%D0%B0%D1%82%D0%B5%D0%BD%D0%BA%D0%BE_%22hw_10_4_apply%2C_groupby%2C_pivot_table_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd
from google.colab import drive

In [2]:
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Data/supermarket_sales.csv'
df = pd.read_csv(file_path)

Mounted at /content/drive

In [11]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [18]:
df.groupby(['Branch', 'City'])['gross income'].sum().sort_values(ascending=False)

Branch  City
C       Naypyitaw    5265.1765
A       Yangon       5057.1605
B       Mandalay     5057.0320
Name: gross income, dtype: float64

[текст посилання](https://)2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [19]:
df.groupby(['Branch', 'City'])['gross income'].sum().sort_values(ascending=False)

Branch  City
C       Naypyitaw    5265.1765
A       Yangon       5057.1605
B       Mandalay     5057.0320
Name: gross income, dtype: float64

Naypyitaw в цьому місті магазин з найбільшим прибутком. Від інших міст прибуток відрізняється на малу суму. тому не бачу сенсу відкривати ще один магазин в цьому місті

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [25]:
invoices_by_category = pd.pivot_table(df,index='Branch', columns='Product line', values='Invoice ID', aggfunc='count')
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [29]:
branchmax = invoices_by_category['Electronic accessories'].idxmax()
print(f'Найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" в магазині', branchmax)

Найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" в магазині A

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

1. Щоб відповісти на питання "які користувачі", можна подивитись їх кількість за статевою ознакою. Запит показує що чоловіків та жінок майже однакове розподілення по магазинам

In [33]:
pd.pivot_table(df,index='Branch', columns='Gender', values='Invoice ID', aggfunc='count', margins=True, margins_name='Total')

Gender  Female  Male  Total
Branch
A          161   179    340
B          162   170    332
C          178   150    328
Total      501   499   1000

2. Також цікаве питання розподілення користувачів за методом оплати. Запит також показує майже однакове розподілення по методам оплати

In [35]:
pd.pivot_table(df,index='Branch', columns='Payment', values='Invoice ID', aggfunc='count', margins=True, margins_name='Total')

Payment  Cash  Credit card  Ewallet  Total
Branch
A         110          104      126    340
B         110          109      113    332
C         124           98      106    328
Total     344          311      345   1000

3. Цікаво, який тип клієнтів приносить найбільший прибуток. Теж розподілення майже однакове. Але все ж таки члену клубу магазину приносять прибутку більше. Тож компанії потрібно переводити пересічних клієнтів на членів клубу магазину.

In [38]:
pt = pd.pivot_table(df,     index='Customer type',     values='gross income',     aggfunc='sum',     margins=True,     margins_name='Total')
pt['% of total'] = (pt['gross income'] / pt.loc['Total', 'gross income'] * 100).round(2)

pt

               gross income  % of total
Customer type
Member             7820.164       50.85
Normal             7559.205       49.15
Total             15379.369      100.00